apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: renovate
resources:
  - ../../base/renovate/
  - secrets.yaml
  - test-secret.yaml
patches:
  - path: patch-cron-job.yaml
    target:
      group: batch
      version: v1
      kind: CronJob
      name: renovate
