apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - release.yaml
  - repository.yaml
  - namespace.yaml

configMapGenerator:
  - name: prometheus-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomize-config.yaml
